AWSTemplateFormatVersion: "2010-09-09"
Description: "Template for Clyde River Dashboard"
Parameters:
    ApplicationName:
        Description: "The application name to be used for creating resources and setting associated properties."
        Type: "String"
        AllowedPattern: "^[0-9a-z]+(?:-[0-9a-z]+)*$"  # Enforces alphanumeric segments delimited by a hyphen.
        Default: "clyde-river-dashboard"
    EnvironmentName:
        Description: "The environment name to be used for creating resources and setting associated properties."
        Type: "String"
        AllowedValues: ["development", "testing", "production"]
        Default: "development"
Resources:
    CloudFrontDistribution:
        Type: "AWS::CloudFront::Distribution"
        Properties:
            DistributionConfig:
                Enabled: true
                Origins:
                    -   Id: !Sub "${ApplicationName}-${EnvironmentName}-origin"
                        DomainName: !Sub "${S3Bucket}.s3.${AWS::Region}.amazonaws.com"
                        S3OriginConfig:
                            OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}"
                DefaultCacheBehavior:
                    TargetOriginId: !Sub "${ApplicationName}-${EnvironmentName}-origin"
                    AllowedMethods:
                        -   "GET"
                        -   "HEAD"
                    CachePolicyId: "658327ea-f89d-4fab-a63d-7e88639e58f6"  # References the managed policy "CachingOptimized".
                    ViewerProtocolPolicy: "redirect-to-https"
                DefaultRootObject: "index.html"
                ViewerCertificate:
                    CloudFrontDefaultCertificate: true
            Tags:
                -   Key: "Application"
                    Value: !Ref "ApplicationName"
                -   Key: "Environment"
                    Value: !Ref "EnvironmentName"
    CloudFrontOriginAccessIdentity:
        Type: "AWS::CloudFront::CloudFrontOriginAccessIdentity"
        Properties:
            CloudFrontOriginAccessIdentityConfig:
                Comment: "Permits access to the S3 Bucket."
    S3Bucket:
        Type: "AWS::S3::Bucket"
        Properties:
            AccessControl: "Private"
            BucketName: !Sub "${ApplicationName}-${EnvironmentName}-bucket"
            Tags:
                -   Key: "Application"
                    Value: !Ref "ApplicationName"
                -   Key: "Environment"
                    Value: !Ref "EnvironmentName"
    S3BucketPolicy:
        Type: "AWS::S3::BucketPolicy"
        Properties:
            Bucket: !Ref "S3Bucket"
            PolicyDocument:
                Version: "2012-10-17"
                Statement:
                    -   Action: "s3:GetObject"
                        Effect: "Allow"
                        Resource: !Sub "${S3Bucket.Arn}/*"
                        Principal:
                            CanonicalUser: !GetAtt "CloudFrontOriginAccessIdentity.S3CanonicalUserId"
Outputs:
    CloudFrontDistributionId:
        Description: "The physical ID of the CloudFront Distribution, which is required for cache invalidation."
        Value: !Ref CloudFrontDistribution
